baseURL = "https://pabes.me"
title = "Patrick Abraham"
theme = "medium-pabes"
languageCode = "en-US"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true
publishDir = "docs"
summaryLength = 10
[params]
  description = "Cybersecurity Detection and Automation"
  copyright = ""
  dark = "auto"
  highlight = true

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "blog"
    title = "blog"
    url = "/blog/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/"
    weight = 10

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
